insert into specificqualification (id, Description) values ('SEC-45', 'Secretarial work, at least 45 words per minute');
insert into specificqualification (id, Description) values ('SEC-60', 'Secretarial work, at least 60 words per minute');
insert into specificqualification (id, Description) values ('CLERK', 'General clerking work');
insert into specificqualification (id, Description) values ('PRG-VB', 'Programmer, Visual Basic');
insert into specificqualification (id, Description) values ('PRG-C++', 'Programmer, C++');
insert into specificqualification (id, Description) values ('DBA-ORA', 'Database Administrator, Oracle');
insert into specificqualification (id, Description) values ('DBA-DB2', 'Database Administrator,IBMDB2');
insert into specificqualification (id, Description) values ('DBA-SQLSERV', 'Database Administrator, MS SQL Server');
insert into specificqualification (id, Description) values ('SYS-1', 'Systems Analyst, level 1');
insert into specificqualification (id, Description) values ('SYS-2', 'Systems Analyst, level2');
insert into specificqualification (id, Description) values ('NW-NOV', 'Network Administrator, Novell experience');
insert into specificqualification (id, Description) values ('WD-CF', 'Web Developer, ColdFusion');
